<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>org.sebastiandev.trip</groupId><artifactId>trip-platform</artifactId><version>1.0.0-SNAPSHOT</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>notification-service</artifactId>
    <dependencies>
        <dependency><groupId>${project.groupId}</groupId><artifactId>contracts</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-grpc</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-mongodb-panache</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-messaging-kafka</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-jackson</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-mailer</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-smallrye-health</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-opentelemetry</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-micrometer-registry-prometheus</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-logging-json</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-smallrye-fault-tolerance</artifactId></dependency>
        <dependency><groupId>io.quarkus</groupId><artifactId>quarkus-junit</artifactId><scope>test</scope></dependency>
    </dependencies>
    <build><plugins><plugin><groupId>${quarkus.platform.group-id}</groupId><artifactId>quarkus-maven-plugin</artifactId></plugin></plugins></build>
    <profiles>
        <profile>
            <id>native</id>
            <properties>
                <skipITs>false</skipITs>
                <quarkus.native.enabled>true</quarkus.native.enabled>
                <quarkus.native.container-build>true</quarkus.native.container-build>
                <quarkus.native.builder-image>mandrel</quarkus.native.builder-image>
                <quarkus.native.builder-image.pull>missing</quarkus.native.builder-image.pull>
                <quarkus.native.native-image-xmx>5g</quarkus.native.native-image-xmx>
                <quarkus.native.march>compatibility</quarkus.native.march>
            </properties>
        </profile>
    </profiles>
</project>
