version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_hotel
    ports:
      - "5432:5432" # Mapeamento da porta
    environment:
      POSTGRES_USER: postgres       # Usuário padrão
      POSTGRES_PASSWORD: password   # Senha do usuário
      POSTGRES_DB: hotel_db         # Banco de dados padrão
    volumes:
      - postgres_hotel_data:/var/lib/postgresql/data # Persistência de dados
    networks:
      - hotel-network                # Rede dedicada ao PostgreSQL e outros serviços

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_hotel
    ports:
      - "8080:80"                    # Acesso ao pgAdmin na porta 8080
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres                     # Garante que o PostgreSQL esteja ativo antes de iniciar o pgAdmin
    networks:
      - hotel-network                # Conecta ao mesmo network do PostgreSQL
    volumes:
      - ./servers.json:/pgadmin4/servers.json # Configuração de servidores (opcional)

volumes:
  postgres_hotel_data: # Corrigido para coincidir com o nome usado no serviço
    driver: local

networks:
  hotel-network:
    driver: bridge
