# syntax=docker/dockerfile:1.7

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6

RUN microdnf install -y ca-certificates curl-minimal \
    && microdnf clean all

WORKDIR /work
ARG MODULE
COPY --chown=1001:0 ${MODULE}/target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["/work/application", "-Dquarkus.http.host=0.0.0.0"]
