x-otel-environment: &otel-environment
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  QUARKUS_OTEL_EXPORTER_OTLP_ENABLED: "true"

x-jaeger-dependency: &jaeger-dependency
  jaeger:
    condition: service_healthy

services:
  api-gateway-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  booking-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  flight-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  hotel-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  transport-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  payment-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  notification-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency

  user-service:
    environment: *otel-environment
    depends_on: *jaeger-dependency
