version: '3.8'

services:
  postgres-hotel:
    image: postgres:15
    container_name: postgres_hotel
    ports:
      - "5432:5432" # Mapeamento da porta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_db
    volumes:
      - postgres_hotel_data:/var/lib/postgresql/data

  postgres-booking:
    image: postgres:15
    container_name: postgres_booking
    ports:
      - "5433:5432" # Mapeamento da porta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    volumes:
      - postgres_booking_data:/var/lib/postgresql/data

volumes:
  postgres_hotel_data:
    driver: local
  postgres_booking_data:
    driver: local
