package org.sebastiandev.trip.user.grpc;
import io.grpc.Status; import io.quarkus.grpc.GrpcService; import io.quarkus.hibernate.reactive.panache.Panache; import io.smallrye.mutiny.Uni; import jakarta.inject.Inject; import java.time.*; import java.util.UUID;
import org.sebastiandev.trip.contracts.event.*; import org.sebastiandev.trip.contracts.grpc.*; import org.sebastiandev.trip.user.domain.UserProfile; import org.sebastiandev.trip.user.messaging.OutboxService; import org.sebastiandev.trip.user.repository.UserProfileRepository;
@GrpcService public class UserProfileGrpcService implements UserProfileService{
 @Inject UserProfileRepository profiles;@Inject OutboxService outbox;
 @Override public Uni<GetUserProfileResponse> getProfile(GetUserProfileRequest request){return profiles.find("subject",request.getSubject()).firstResult().onItem().ifNull().failWith(Status.NOT_FOUND.asRuntimeException()).map(p->GetUserProfileResponse.newBuilder().setProfile(view(p)).build());}
 @Override public Uni<UpsertUserProfileResponse> upsertProfile(UpsertUserProfileRequest request){if(request.getSubject().isBlank()||request.getEmail().isBlank())return Uni.createFrom().failure(Status.INVALID_ARGUMENT.asRuntimeException());return Panache.withTransaction(()->profiles.find("subject",request.getSubject()).firstResult().chain(profile->{OffsetDateTime now=OffsetDateTime.now(ZoneOffset.UTC);boolean fresh=profile==null;UserProfile p=fresh?new UserProfile():profile;if(fresh){p.id=UUID.nameUUIDFromBytes(request.getSubject().getBytes(java.nio.charset.StandardCharsets.UTF_8));p.subject=request.getSubject();p.createdAt=now;}p.email=request.getEmail();p.firstName=request.getFirstName();p.lastName=request.getLastName();p.preferences=request.getPreferencesJson().isBlank()?"{}":request.getPreferencesJson();p.updatedAt=now;Uni<UserProfile> saved=fresh?profiles.persist(p):Uni.createFrom().item(p);return saved.chain(value->enqueue(value).replaceWith(value));})).map(p->UpsertUserProfileResponse.newBuilder().setProfile(view(p)).build());}
 private Uni<Void> enqueue(UserProfile p){EventPayloads.UserProfileChanged payload=new EventPayloads.UserProfileChanged(p.id,p.subject,p.email);return outbox.enqueue(TopicNames.USER_PROFILE_CHANGED,p.id,null,payload).replaceWithVoid();}
 private UserProfileView view(UserProfile p){return UserProfileView.newBuilder().setId(p.id.toString()).setSubject(p.subject).setEmail(p.email).setFirstName(p.firstName==null?"":p.firstName).setLastName(p.lastName==null?"":p.lastName).setPreferencesJson(p.preferences).build();}
}
