package org.sebastiandev.trip.transport.messaging;
import com.fasterxml.jackson.databind.ObjectMapper; import io.quarkus.hibernate.reactive.panache.Panache; import io.smallrye.mutiny.Uni; import jakarta.enterprise.context.ApplicationScoped; import jakarta.inject.Inject; import jakarta.persistence.LockModeType;
import java.time.*; import java.util.UUID; import java.util.function.Supplier; import org.eclipse.microprofile.reactive.messaging.Incoming; import org.eclipse.microprofile.faulttolerance.Retry; import org.sebastiandev.trip.contracts.event.*; import org.sebastiandev.trip.transport.domain.*; import org.sebastiandev.trip.transport.repository.*;
@ApplicationScoped @Retry(maxRetries=3,delay=200) public class TransportCommandConsumer{
 @Inject ObjectMapper mapper;@Inject TransportOfferRepository offers;@Inject TransportReservationRepository reservations;@Inject InboxRepository inbox;@Inject OutboxService outbox;
 @Incoming("reserve-transport")public Uni<Void> reserve(String json){EventEnvelope event=EventSchemaValidator.decodeValidated(mapper,json);EventPayloads.ReservationRequested request=EventCodec.payload(mapper,event,EventPayloads.ReservationRequested.class);return process(event,()->reservations.find("bookingItemId",request.bookingItemId()).firstResult().chain(existing->existing==null?hold(request,event):publish(existing,event.eventId())));}
 private Uni<Void> hold(EventPayloads.ReservationRequested request,EventEnvelope event){OffsetDateTime starts,ends;try{starts=OffsetDateTime.ofInstant(Instant.parse(request.attributes().get("startsAt")),ZoneOffset.UTC);ends=OffsetDateTime.ofInstant(Instant.parse(request.attributes().get("endsAt")),ZoneOffset.UTC);}catch(RuntimeException e){return failure(request,event,"INVALID_INTERVAL");}if(!ends.isAfter(starts))return failure(request,event,"INVALID_INTERVAL");return offers.findById(request.resourceId(),LockModeType.PESSIMISTIC_WRITE).chain(offer->{if(offer==null||!offer.active)return failure(request,event,"TRANSPORT_NOT_FOUND");return reservations.count("offerId = ?1 and status in (?2, ?3) and startsAt < ?4 and endsAt > ?5",request.resourceId(),TransportReservation.Status.HELD,TransportReservation.Status.CONFIRMED,ends,starts).chain(conflicts->{if(conflicts>0)return failure(request,event,"TRANSPORT_UNAVAILABLE");OffsetDateTime now=OffsetDateTime.now(ZoneOffset.UTC);TransportReservation r=new TransportReservation();r.id=UUID.randomUUID();r.bookingId=request.bookingId();r.bookingItemId=request.bookingItemId();r.userId=request.userId();r.offerId=request.resourceId();r.startsAt=starts;r.endsAt=ends;r.status=TransportReservation.Status.HELD;r.amountMinor=offer.priceMinor;r.currency=offer.currency;r.holdUntil=request.holdUntil();r.createdAt=now;r.updatedAt=now;return reservations.persist(r).chain(()->publish(r,event.eventId()));});});}
 @Incoming("confirm-transport")public Uni<Void> confirm(String json){EventEnvelope event=EventSchemaValidator.decodeValidated(mapper,json);EventPayloads.ReservationAction request=EventCodec.payload(mapper,event,EventPayloads.ReservationAction.class);return process(event,()->reservations.findById(request.reservationId()).chain(r->{if(r==null||!r.bookingItemId.equals(request.bookingItemId()))return raw(request.bookingId(),request.bookingItemId(),request.reservationId(),0,"XXX","FAILED","RESERVATION_NOT_FOUND",TopicNames.TRANSPORT_FAILED,event.eventId());if(r.status==TransportReservation.Status.CONFIRMED)return publish(r,event.eventId());if(r.status!=TransportReservation.Status.HELD||r.holdUntil.isBefore(OffsetDateTime.now(ZoneOffset.UTC)))return outcome(r,"FAILED","HOLD_EXPIRED",TopicNames.TRANSPORT_FAILED,event.eventId());r.status=TransportReservation.Status.CONFIRMED;r.updatedAt=OffsetDateTime.now(ZoneOffset.UTC);return publish(r,event.eventId());}));}
 @Incoming("cancel-transport")public Uni<Void> cancel(String json){EventEnvelope event=EventSchemaValidator.decodeValidated(mapper,json);EventPayloads.ReservationAction request=EventCodec.payload(mapper,event,EventPayloads.ReservationAction.class);return process(event,()->reservations.findById(request.reservationId()).chain(r->{if(r==null)return raw(request.bookingId(),request.bookingItemId(),request.reservationId(),0,"XXX","CANCELLED",null,TopicNames.TRANSPORT_CANCELLED,event.eventId());r.status=TransportReservation.Status.CANCELLED;r.updatedAt=OffsetDateTime.now(ZoneOffset.UTC);return publish(r,event.eventId());}));}
 private Uni<Void> process(EventEnvelope event,Supplier<Uni<Void>> action){return Panache.withTransaction(()->inbox.findById(event.eventId()).chain(existing->{if(existing!=null)return Uni.createFrom().voidItem();return action.get().chain(()->{InboxEvent done=new InboxEvent();done.eventId=event.eventId();done.type=event.type();done.processedAt=OffsetDateTime.now(ZoneOffset.UTC);return inbox.persist(done).replaceWithVoid();});}));}
 private Uni<Void> failure(EventPayloads.ReservationRequested r,EventEnvelope e,String reason){return raw(r.bookingId(),r.bookingItemId(),null,0,r.currency(),"FAILED",reason,TopicNames.TRANSPORT_FAILED,e.eventId());}
 private Uni<Void> publish(TransportReservation r,UUID cause){String topic=switch(r.status){case HELD->TopicNames.TRANSPORT_HELD;case CONFIRMED->TopicNames.TRANSPORT_CONFIRMED;case CANCELLED,EXPIRED->TopicNames.TRANSPORT_CANCELLED;};return outcome(r,r.status.name(),null,topic,cause);}
 private Uni<Void> outcome(TransportReservation r,String status,String reason,String topic,UUID cause){return raw(r.bookingId,r.bookingItemId,r.id,r.amountMinor,r.currency,status,reason,topic,cause);}
 private Uni<Void> raw(UUID booking,UUID item,UUID reservation,long amount,String currency,String status,String reason,String topic,UUID cause){return outbox.enqueue(topic,booking,cause,new EventPayloads.ReservationOutcome(booking,item,reservation,amount,currency,status,reason)).replaceWithVoid();}
}
