package org.sebastiandev.trip.transport.grpc;
import io.grpc.Status; import io.quarkus.grpc.GrpcService; import io.quarkus.hibernate.reactive.panache.Panache; import io.quarkus.hibernate.reactive.panache.common.WithSession; import io.smallrye.mutiny.Uni; import jakarta.inject.Inject; import java.time.*; import java.util.UUID; import org.sebastiandev.trip.contracts.grpc.*; import org.sebastiandev.trip.transport.domain.*; import org.sebastiandev.trip.transport.repository.*;
@GrpcService public class TransportGrpcService implements TransportQueryService{
 @Inject TransportOfferRepository offers;@Inject TransportReservationRepository reservations;
 @Override @WithSession public Uni<SearchTransportsResponse> searchTransports(SearchTransportsRequest request){OffsetDateTime start=time(request.getStartsAt()),end=time(request.getEndsAt());String type=request.getTransportType().trim().toLowerCase();Uni<java.util.List<TransportOffer>> search=type.isEmpty()?offers.find("active = true order by providerName").list():offers.find("lower(transportType) = ?1 and active = true order by providerName",type).list();return search.chain(list->{Uni<SearchTransportsResponse.Builder> chain=Uni.createFrom().item(SearchTransportsResponse.newBuilder());for(TransportOffer offer:list)chain=chain.chain(builder->available(offer.id,start,end).map(ok->builder.addTransports(view(offer,ok))));return chain.map(SearchTransportsResponse.Builder::build);});}
 @Override @WithSession public Uni<GetTransportResponse> getTransport(GetTransportRequest request){try{UUID id=UUID.fromString(request.getTransportId());OffsetDateTime start=time(request.getStartsAt()),end=time(request.getEndsAt());return offers.findById(id).onItem().ifNull().failWith(Status.NOT_FOUND.asRuntimeException()).chain(offer->available(id,start,end).map(ok->GetTransportResponse.newBuilder().setTransport(view(offer,ok)).build()));}catch(RuntimeException e){return Uni.createFrom().failure(Status.INVALID_ARGUMENT.asRuntimeException());}}
 @Override public Uni<CreateTransportResponse> createTransport(CreateTransportRequest request){TransportOffer offer=new TransportOffer();offer.id=UUID.randomUUID();offer.transportType=request.getTransportType();offer.providerName=request.getProviderName();offer.vehicleDetailsJson=request.getVehicleDetailsJson();offer.priceMinor=request.getPrice().getAmountMinor();offer.currency=request.getPrice().getCurrency();offer.active=true;return Panache.withTransaction(()->offers.persist(offer)).map(saved->CreateTransportResponse.newBuilder().setTransport(view(saved,true)).build());}
 private Uni<Boolean> available(UUID id,OffsetDateTime start,OffsetDateTime end){return reservations.count("offerId = ?1 and status in (?2, ?3) and startsAt < ?4 and endsAt > ?5",id,TransportReservation.Status.HELD,TransportReservation.Status.CONFIRMED,end,start).map(count->count==0);}
 private TransportView view(TransportOffer o,boolean ok){return TransportView.newBuilder().setId(o.id.toString()).setTransportType(o.transportType).setProviderName(o.providerName).setVehicleDetailsJson(o.vehicleDetailsJson).setPrice(Money.newBuilder().setCurrency(o.currency).setAmountMinor(o.priceMinor)).setAvailable(ok).build();}
 private OffsetDateTime time(com.google.protobuf.Timestamp value){return OffsetDateTime.ofInstant(Instant.ofEpochSecond(value.getSeconds(),value.getNanos()),ZoneOffset.UTC);}
}
